spring:
  application:
    name: clinicX

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicx?currentSchema=public
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
