spring:
  application:
    name: clinicX

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driverClassName: ${spring.datasource.driverClassName}

#  profiles:
#    active: postgres  # Default to H2 for development. Use 'postgres' for PostgreSQL

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: ${spring.jpa.properties.hibernate.dialect}
        hbm2ddl:
          auto: validate
        format_sql: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    baseline-version: 0
    out-of-order: true
    locations: ${flyway.locations}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18081/realms/clinicx-dev
          jwk-set-uri: http://localhost:18081/realms/clinicx-dev/protocol/openid-connect/certs

# ClinicX specific configuration
clinicx:
  tenant:
    mode: single  # Options: single, multi
    default-id: default-tenant

  security:
    keycloak:
      realm: clinicx-dev
      client-id: clinicx-backend
      client-secret: tHFYKZ1bgyLz6dOWHsAa8ir3yXdzbcjk

# Logging configuration
logging:
  level:
    root: INFO
    sy.sezar.clinicx: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Application-specific configuration
app:
  date:
    formats:
      datetime:
        - "yyyy-MM-dd'T'HH:mm:ss"
        - "yyyy-MM-dd'T'HH:mm:ss'Z'"
        - "yyyy-MM-dd'T'HH:mm:ssX"
        - "yyyy-MM-dd HH:mm:ss"
      date: "yyyy-MM-dd"
    default-timezone: UTC

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  security-schemes:
    bearer-jwt:
      type: http
      scheme: bearer
      bearer-format: JWT
      description: "Enter JWT Bearer token"
