# Development profile with Keycloak
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/clinicx?currentSchema=public
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    locations: classpath:db/migration,classpath:db/local_demo_data

  # Allow circular references in dev (for rapid development)
  main:
    allow-circular-references: true


# Reduced logging in development
logging:
  level:
    root: INFO
    sy.sezar.clinicx: DEBUG
    org.springframework.security: DEBUG  # Reduce security logs
    org.springframework.security.oauth2: DEBUG

# CORS configuration for development
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:4200
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  exposed-headers:
    - Authorization
  allow-credentials: true


# TODO merge clinix and app configuration
# Development-specific tenant configuration
clinicx:
  tenant:
    mode: multi  # Start with single tenant for simplicity
    default-id: dev-tenant-001


# Application-specific configuration
app:
  # Multi-tenant configuration
  multi-tenant:
    enabled: true
    tenant:
      default-id: default
    default-realm: master

  # Domain configuration
  domain: clinicx.com

# Keycloak configuration
keycloak:
  auth-server-url: http://localhost:18081
  master-realm: master
  admin-client-id: admin-cli
  admin-username: admin
  admin-password: admin
