spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicx?currentSchema=public
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    locations: classpath:db/migration,classpath:db/local_demo_data
