spring:
  datasource:
    url: jdbc:h2:mem:clinicx;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


  flyway:
    locations: classpath:db/migration-h2,classpath:db/local_demo_data-h2

