spring:
  application:
    name: clinicX

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicx?currentSchema=public
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baselineOnMigrate: true
    baseline-version: 0
    out-of-order: true # NOTE only for local development
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
